//
// This file was generated by the JPA Modeler
//
package com.hugo.ente.models;

import java.io.Serializable;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;

@Entity
public class Application extends AbstractEntity implements Serializable {

    @ManyToMany(targetEntity = HostMachine.class)
    private Set<HostMachine> hostMachines;

    @Column(unique = true, nullable = false)
    @Basic
    private String name;

    @Column(length = 1023)
    @Basic
    private String description;


    public Set<HostMachine> getHostMachines() {
        return this.hostMachines;
    }

    public void setHostMachines(Set<HostMachine> hostMachines) {
        this.hostMachines = hostMachines;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
